baseurl: "https://thepetitemarketing.netlify.app/ "
languageCode: en-us
title: thepetitemarketing
theme: parsa-hugo
summaryLength: '10'
paginate: 6
googleAnalytics: ''
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  address: Rome,Italy
  author: Anastasiia Ivanova
  bio: Personal blog about marketing and not only
  contact_form_action: "ivanova.anastasiia.96@gmail.com"
  cookies:
    enable: yes
    expire_days: 2
  copyright: Copyright &copy; 2020 a theme by [themefisher.com](themefisher.com)
  description: Personal blog about marketing and not only
  email: "ivanova.anastasiia.96@gmail.com"
  home: Home
  instafeed:
    access_token: IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn
    enable: yes
  layout: '1'
  logo: config_files/my_logo_2.png
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/slick/slick.css
      - link: plugins/themify-icons/themify-icons.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/headroom/headroom.js
      - link: plugins/instafeed/instafeed.min.js
      - link: plugins/masonry/masonry.js
      - link: plugins/reading-time/readingTime.min.js
      - link: plugins/smooth-scroll/smooth-scroll.js
      - link: plugins/search/fuse.min.js
      - link: plugins/search/mark.js
      - link: plugins/search/search.js
  preloader: yes
  search: yes
  social:
    - icon: ti-instagram
      url: "https://www.instagram.com/theanabravo/"
    - icon: ti-linkedin
      url: "https://www.linkedin.com/in/anastasiia-ivanova-19011996/"

menu:
  main:
    - name: Homepage
      url: homepage/home-1
      weight: 1
    - name: About
      url: about
      weight: 2
    - name: Contact
      url: contact
      weight: 3
    - name: IG
      url: "https://www.instagram.com/theanabravo/"
      weight: 4

